[package]
name = "rust_crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["gzip", "brotli", "deflate", "rustls-tls"] }
scraper = "0.18"
tokio = { version = "1", features = ["full"] }
